baseURL = "https://markogata.com"
languageCode = "en"
title = "Mark Ogata"
theme = "hugo-coder"

paginate = 20

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
  author = "Mark Ogata"
  info = "Anticipation"
  description = "Mark Ogata's personal website"
  keywords = "blog,developer,personal"
  avatarurl = "img/logo.png"

  favicon_32 = "img/logo.png"
  # favicon_16 = "/img/favicon-16x16.png"

  touchIcon = "/images/apple-touch-icon.png"
  since = 2022

  math = false

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

#   customCSS = ["css/custom.css"]
#   customSCSS = ["scss/custom.scss"]
#   customJS = ["js/custom.js"]
  commentoURL = "https://cdn.commento.io"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/Clamepending/"
[[params.social]]
  name = "Twitter"
  icon = "fa fa-twitter fa-2x"
  weight = 3
  url = "https://twitter.com/SotaOgata/"
[[params.social]]
  name = "Instagram"
  icon = "fa fa-instagram fa-2x"
  weight = 4
  url = "https://www.instagram.com/sotaogata/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 5
  url = "https://www.linkedin.com/in/sota-mark-ogata-153b06212/"
[[params.social]]
  name = "YouTube"
  icon = "fa fa-youtube-play fa-2x"
  weight = 5
  url = "https://www.youtube.com/channel/UCr61h4mtQwuyLr2ba_rrt_Q"


[languages.en]
languageName = "English"

# Menu links
[[languages.en.menu.main]]
  name = "Posts"
  weight = 1
  url  = "posts/"
[[languages.en.menu.main]]
  name = "About"
  weight = 2
  url = "about/"


[languages.jp]
  languageName = "日本語"
  title = "緒方奏太"
[languages.jp.params]
  author = "緒方奏太マーク"
  info = "悔いのない一日を！"
  description = "個人のブログ"
  keywords = "個人,ブログ,ロボット"

  

[[languages.jp.menu.main]]
  name = "投稿"
  weight = 1
  url  = "posts/"
[[languages.jp.menu.main]]
  name = "誰？"
  weight = 2
  url = "about/"

