baseURL: 
languageCode: en-us
title: Mark Ogata
theme: hugo-coder


# params:
#   ShowReadingTime: true
#   ShowShare Buttons: true





menu:
  main:
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 10  
    - identifier: Categories
      name: Categories
      url: /Categories/
      weight: 20  
    - identifier: Projects
      name: Projects
      url: /Projects/
      weight: 30